### ISSUE TITLE
requirement.txt file contain invalid modules

### ISSUE THREAD

**Issue by xalgord** [0x240x23elu/JSScanner#1]
i am unable to install os and sys module by giving command pip3 install -r requirements.txt
```
pip3 install -r requirements.txt 
Requirement already satisfied: requests in /home/xalgord/.local/lib/python3.8/site-packages (from -r requirements.txt (line 1)) (2.23.0)
Requirement already satisfied: urllib3 in /usr/lib/python3/dist-packages (from -r requirements.txt (line 2)) (1.25.8)
ERROR: Could not find a version that satisfies the requirement sys (from -r requirements.txt (line 3)) (from versions: none)
ERROR: No matching distribution found for sys (from -r requirements.txt (line 3))
```

**Comment by tequreq** [comment]
`pip3 install -r  requirements.txt` after out error log under this message. And the site not found : https://pypi.org/simple/sys/



```Requirement already satisfied: requests in /root/.local/lib/python3.6/site-packages (from -r requirements.txt (line 1))
Requirement already satisfied: urllib3 in /root/.local/lib/python3.6/site-packages (from -r requirements.txt (line 2))
Collecting sys (from -r requirements.txt (line 3))
Exception:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/pip/basecommand.py", line 215, in main
    status = self.run(options, args)
  File "/usr/lib/python3/dist-packages/pip/commands/install.py", line 353, in run
    wb.build(autobuilding=True)
  File "/usr/lib/python3/dist-packages/pip/wheel.py", line 749, in build
    self.requirement_set.prepare_files(self.finder)
  File "/usr/lib/python3/dist-packages/pip/req/req_set.py", line 380, in prepare_files
    ignore_dependencies=self.ignore_dependencies))
  File "/usr/lib/python3/dist-packages/pip/req/req_set.py", line 554, in _prepare_file
    require_hashes
  File "/usr/lib/python3/dist-packages/pip/req/req_install.py", line 278, in populate_link
    self.link = finder.find_requirement(self, upgrade)
  File "/usr/lib/python3/dist-packages/pip/index.py", line 465, in find_requirement
    all_candidates = self.find_all_candidates(req.name)
  File "/usr/lib/python3/dist-packages/pip/index.py", line 423, in find_all_candidates
    for page in self._get_pages(url_locations, project_name):
  File "/usr/lib/python3/dist-packages/pip/index.py", line 568, in _get_pages
    page = self._get_page(location)
  File "/usr/lib/python3/dist-packages/pip/index.py", line 683, in _get_page
    return HTMLPage.get_page(link, session=self.session)
  File "/usr/lib/python3/dist-packages/pip/index.py", line 795, in get_page
    resp.raise_for_status()
  File "/usr/share/python-wheels/requests-2.18.4-py2.py3-none-any.whl/requests/models.py", line 935, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://pypi.org/simple/sys/
```

**Comment by 0x240x23elu** [comment]
Hi Line number 3 sys is Module is already installed in python3.
please run directly python3 JSScanner.py
if any problem then let me know

**Comment by 0x240x23elu** [comment]
https://stackoverflow.com/questions/54355608/how-can-i-install-the-os-package-of-python-using-the-anaconda-prompt

**Comment by xalgord** [comment]
i know os and sys modules are inbuilt but the problem is it shows error on runtime

**Comment by shelu16** [comment]
Can you show us screen shot after run  python3 JSScanner.py

**Comment by krishna-kaushal** [comment]
![Screenshot from 2021-01-23 21-53-13](https://user-images.githubusercontent.com/48483027/105622328-b4d47700-5e36-11eb-8fa7-6d46ca8fd8d5.png)

**Comment by xalgord** [comment]
![Screenshot from 2021-01-23 21-56-58](https://user-images.githubusercontent.com/48483027/105622376-2a404780-5e37-11eb-9fb2-8cf5747b6519.png)

**Comment by 0x240x23elu** [comment]
Hi 
http://3.datastax.com/ domain is not exist. check first 
and other is live so data is there
![image](https://user-images.githubusercontent.com/52744492/105623268-79d64180-5e3e-11eb-859a-5af9d1a20da2.png)

**Comment by 0x240x23elu** [comment]
![image](https://user-images.githubusercontent.com/52744492/105623295-9ffbe180-5e3e-11eb-8567-8b947729ca63.png)
